# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Mchn.ch
  fr: Mchn.ch
email: alin@mchn.ch
description:
  en: Personal blog!
 fr: Écrivez une super description de votre nouveau site ici. Vous pouvez modifier cette ligne dans _config.yml. Elle apparaîtra dans la balise meta description (pour les résultats sur Google) et dans le fil RSS feed.xml.
index:
  en:
  fr: accueil.html
feed:
  en: /feed.xml
  fr: /flux.xml
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://mchn.ch" # the base hostname & protocol for your site
twitter_username: alinmechenici
github_username:  alinmechenici

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal
